version: '3.8'

services:
  web:
    build: .
    image: mohitmakwana/student_website:latest
    command: gunicorn Student_Website.wsgi --bind=0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  static_volume:
    driver: local
    # Optional: define the host path to ensure consistency, if required
    driver_opts:
      o: bind
      type: none
      device: ./static

  media_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./media
