services:
  gunicorn:
    build: 
      context: .
    command: bash -c "python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn 'Student_Website.wsgi' --bind=0.0.0.0:8000"
    image: studentmanagement
    container_name: studentmng
    expose:  # Use 'expose' instead of 'ports' to make it accessible to Nginx only
      - 8000
    network_mode : host
  nginx:
    image: nginx
    # expose:
    #   - 80
    ports:
      - 8080:80  # Expose Nginx on port 8080 of the host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx configuration file
    depends_on:
      - gunicorn
