# Generated by Django 5.0.6 on 2024-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_sub_syllabus_type_gtuexam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtuexam',
            name='sub_academic_term',
            field=models.CharField(max_length=5, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='gtuexam',
            name='sub_sem',
            field=models.IntegerField(default=0, verbose_name='Sem'),
        ),
        migrations.AlterField(
            model_name='gtuexam',
            name='sub_session',
            field=models.CharField(max_length=6, verbose_name='Session'),
        ),
    ]
