# Generated by Django 5.0.6 on 2024-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0011_rename_save_marks_student_marks_marks_entered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_marks',
            name='stu_enroll',
            field=models.CharField(default='enrollmentno', max_length=12, verbose_name='Student Enrollment Number'),
        ),
    ]
