# Generated by Django 5.0.6 on 2024-07-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0012_alter_student_marks_stu_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_enroll',
            field=models.CharField(default=0, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Student Enrollment Number'),
        ),
    ]
