# Generated by Django 5.0.6 on 2024-07-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0013_alter_student_stu_enroll'),
        ('faculty', '0002_alter_faculty_records_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='exam_type',
            field=models.CharField(default='S2023-Regular', max_length=14, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='is_remedial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='Assigned_Sub_Faculty',
            field=models.ForeignKey(default=11, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty_records', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='stu_enroll',
            field=models.CharField(default='enrollmentno', max_length=12, verbose_name='Enrollment'),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='stu_sem',
            field=models.IntegerField(default=5, verbose_name='Semester'),
        ),
    ]
