# Generated by Django 5.0.6 on 2024-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0014_student_marks_exam_type_student_marks_is_remedial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='is_passout',
            field=models.BooleanField(default=False),
        ),
    ]
