# Generated by Django 5.0.6 on 2024-07-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0015_student_marks_is_passout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_marks',
            name='is_passout',
        ),
        migrations.AddField(
            model_name='student',
            name='is_passout',
            field=models.BooleanField(default=False, verbose_name='Passout'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_passed',
            field=models.BooleanField(default=True, verbose_name='Passed'),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='is_passed',
            field=models.BooleanField(default=True, verbose_name='Passed'),
        ),
    ]
