# Generated by Django 5.0.6 on 2024-07-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0016_remove_student_marks_is_passout_student_is_passout_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_from_xlsx',
            new_name='upload_from_xlsxd',
        ),
    ]
