# Generated by Django 5.0.6 on 2024-07-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0017_rename_upload_from_xlsx_upload_from_xlsxd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_from_xlsxd',
            new_name='Upload_from_xlsx',
        ),
    ]
