# Generated by Django 5.0.6 on 2024-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0023_alter_publish_result_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adhar_no',
            field=models.CharField(default=0, max_length=12, verbose_name='Adhar No.'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=50),
        ),
    ]
