# Generated by Django 5.0.6 on 2024-08-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0024_student_adhar_no_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NONE', 'None'), ('OTHER', 'Other')], default='NONE', max_length=50),
        ),
    ]
