# Generated by Django 5.0.6 on 2024-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0025_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Student/profile_pic/'),
        ),
    ]
